### PR TITLE
Master

### PR DESCRIPTION
**Pull request by yusfate4**
I created the comment suggestion

### CODE REVIEW

**Comment by devtuyi** [comment]
> 

Please send the files in zip format to Prisca with your repo link. 
The resources folder is not the appropriate place to put html files. 
Laravel uses blade template

**Comment by yusfate4** [comment]
Alright, I will do that now

**Comment by ti-oluwa** [comment]
Please @yusfate4 your submission is being reviewed. Also, you work is just a part of the download page. Hence, we need to wait for the remaining part to be completed after which it will be compiled into one template (download page template) and sent to Prisca.

**Comment by ti-oluwa** [comment]
@soluwatuyi Pull request made to the Frontend branch does not affect the 'main' or 'secondary' branches. Please do not close their pull requests, this is the only way their work and submissions can reflect on the project/repo.

**Review by ti-oluwa — APPROVED** [review]
Good job sir.

**Comment by ti-oluwa** [comment]
@ElSam20 Please can you review this. I think its okay and ready for merge.

**Comment by yusfate4** [comment]
> Please @yusfate4 your submission is being reviewed. Also, you work is just a part of the download page. Hence, we need to wait for the remaining part to be completed after which it will be compiled into one template (download page template) and sent to Prisca.

@ti-oluwa. Do you mean I should hold on for now? I shouldn't forward the zip file to Prisca

**Comment by ti-oluwa** [comment]
> > Please @yusfate4 your submission is being reviewed. Also, you work is just a part of the download page. Hence, we need to wait for the remaining part to be completed after which it will be compiled into one template (download page template) and sent to Prisca.
> 
> @ti-oluwa. Do you mean I should hold on for now? I shouldn't forward the zip file to Prisca

Yes sir @yusfate4. Your template is just part of a whole. when we merge everything, it will be sent to Prisca

**Pull request merged**
